/* All state below is ephemeral prototype state. No backend, storage or API. */
const $=(s,r=document)=>r.querySelector(s), $$=(s,r=document)=>[...r.querySelectorAll(s)];
const state={scene:'today',hasPlan:true,supplement:'',settingsTab:'preferences',settings:{travel:'步行',rhythm:'适当穿插休息',lunchStart:'11:30',lunchEnd:'13:00',dinnerStart:'17:30',dinnerEnd:'19:00',note:'做数学时，给我留一点查笔记的时间。',campus:'卫津路校区',dorm:'六里台宿舍',study:'图书馆'},draft:null,opener:null};
let toastTimer;
function notify(text){$('#toast').textContent=text;$('#toast').hidden=false;clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('#toast').hidden=true,3200)}
function escapeHTML(s){return String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function heading(label,title,subtitle='',actions=''){return `<div class="page-heading"><div><p class="eyebrow">${label}</p><h1>${title}</h1>${subtitle?`<p class="sub">${subtitle}</p>`:''}</div><div class="heading-actions">${actions}</div></div>`}
function today(){return `${heading('9 月 12 日 · 周六','今天，先做好眼前这件事。','',`<span class="clock">14:00</span><button class="quiet" data-replan>重新安排今天 ↗</button>`)}
 <div class="today-grid"><div>
  <section class="current-action" aria-label="当前行动">
   <div class="action-kicker"><span class="live-label"><i></i>现在 · 14:00—15:30</span><span>图书馆</span></div>
   <div class="action-content"><div><h2>写作业</h2><p>这一段，先专心写到 15:30。</p></div><div class="duration"><strong>90</strong><span>分钟</span><small>本段安排</small></div></div>
   <div class="action-divider"><button class="primary" data-feedback>更新进度 <span>↗</span></button><button class="quiet" data-detail="why">为什么先做这件事？</button></div>
   <p class="action-reason">离晚课还有充裕时间，先留出一段完整的学习时间。</p>
  </section>
  <section class="next-section"><div class="eyebrow">接下来</div><div><strong>背单词</strong><p>15:30—16:30 · 图书馆 · 60 分钟</p></div><button class="quiet" data-detail="next" aria-label="查看下一安排">↗</button></section>
  <section class="mini-ledger"><div class="section-title"><h2>今天余下的安排</h2><a class="quiet" href="#timeline">完整时间线 →</a></div>
   <div class="ledger-row"><time>17:00—17:40</time><span>吃晚饭</span><small>学三食堂</small></div>
   <div class="ledger-row"><time>19:00—20:30</time><span>上课</span><small>第九教学楼 · 固定</small></div>
  </section>
  <div class="feedback-inline"><span>进度、位置或安排有变化？</span><button class="quiet" data-feedback>告诉 CampusFlow ↗</button></div>
 </div><aside class="side-note"><h3>下一个固定安排</h3><div class="fixed-time">19:00</div><h2>上课</h2><p>第九教学楼 · 到 20:30</p>
  <div class="route-strip"><strong>18:46 从学三食堂出发</strong><div class="route-line">学三食堂<span></span>第九教学楼</div><small>步行约 4 分钟，另留进楼与课前准备时间。</small><br><button class="quiet small" data-detail="route">查看出行安排 →</button></div>
  <div class="side-tip">晚饭后的空档较长。<br>可以休息一下，出发前再收拾东西。</div>
 </aside></div>`}
function empty(){return `<div class="empty-layout"><section class="empty-main"><p class="eyebrow blue">今天还没有计划</p><h1>接下来的时间，<br>想做些什么？</h1><p class="intro">把要做的事写下来，有课、有截止时间也一起告诉我。</p>
 <form id="plan-form"><div class="composer"><textarea aria-label="接下来想做什么" placeholder="下午想在图书馆写作业、背单词，19:00 去九教上课。" required></textarea><div class="composer-bottom"><label class="location-inline"><span aria-hidden="true">⌖</span><input aria-label="当前位置（可选）" placeholder="当前位置（可选）"></label><button class="primary" type="submit">帮我安排 <span>→</span></button></div></div></form>
 <div class="input-example"><span>不知道怎么开始？</span><button class="quiet" id="fill-example">试试“课前写作业，留时间吃晚饭”</button></div>
 <div class="starter-tool"><span class="tool-symbol" aria-hidden="true">▤</span><div><strong>难以估计任务时间？</strong><p>有材料，先看看大约要花多久。</p></div><a class="quiet" href="#material">打开估时工具 →</a></div>
 <div class="onboard-link">课表、地点和日常偏好，可以在 <button class="quiet small" data-settings>个人设置</button> 中保存。</div>
 </section><aside class="empty-side"><div class="date-number">12</div><div class="date-label">九月 · 星期六</div><div class="empty-aside-line">今天还没有安排。<br>先从最想完成的一件事开始。</div></aside></div>`}
const events=[
 ['14:00','15:30','写作业','图书馆 · 当前行动','90 分钟','current'],
 ['15:30','16:30','背单词','图书馆','60 分钟',''],
 ['16:30','16:42','收拾东西，步行去学三食堂','收拾 5 分钟 · 步行约 7 分钟','出行','transit'],
 ['16:42','17:00','到食堂，休息一下','','18 分钟','transit'],
 ['17:00','17:40','吃晚饭','学三食堂','40 分钟',''],
 ['17:40','18:41','自由休息','饭后留一段空档','61 分钟',''],
 ['18:41','18:50','收拾东西，步行去第九教学楼','收拾 5 分钟 · 步行约 4 分钟','出行','transit'],
 ['18:50','19:00','进楼找教室，准备上课','','10 分钟','transit'],
 ['19:00','20:30','上课','第九教学楼','固定安排','fixed']
];
function timeline(){return `${heading('一天的安排','今天的时间线','学习、吃饭和路上的时间，放在一起看。',`<button class="secondary" data-feedback>有变化，调整一下</button>`)}<div class="timeline-layout"><div><div class="day-strip"><strong>9 月 12 日 · 周六</strong><span>14:00—20:30</span><span style="margin-left:auto">卫津路校区</span></div><div class="timeline">${events.map(e=>`<div class="time-row ${e[5]}"><time>${e[0]}<small>${e[1]}</small></time><div><h3>${e[2]}</h3>${e[3]?`<p>${e[3]}</p>`:''}</div><span class="time-meta">${e[4]}</span></div>`).join('')}</div></div><aside class="timeline-aside"><p class="eyebrow">今天的节奏</p><div class="stat"><p>学习时间</p><strong>150</strong><small>分钟</small></div><div class="stat"><p>路上步行</p><strong>11</strong><small>分钟 · 2 段</small></div><div class="stat"><p>固定安排</p><strong>1</strong><small>项晚课</small></div><p class="time-note">空档也属于计划的一部分。<br>外部等待不会被算成专注时间。</p><button class="quiet small" data-detail="route">查看出行安排 ↗</button></aside></div>`}
function material(){return `${heading('辅助工具 / 材料估时','难以估计任务时间？','把要处理的材料交给 CampusFlow，先了解工作量。',`<a class="quiet" href="#today">返回今天 →</a>`)}<div class="material-layout"><section class="material-bench">
 <div class="file-line"><span class="file-tag">DOCX</span><div><strong>本科生综合素质测评考核表【主观评价部分】</strong><small>Word 文档 · 已读取</small></div><button class="quiet small" id="change-file">更换</button><input type="file" accept=".docx,.pdf,.png,.jpg,.jpeg" id="material-file" hidden></div>
 <h2 class="estimate-name">填写测评表，准备主观评价</h2><p class="eyebrow">根据目前识别到的内容，先估算</p><div class="estimate-numbers"><div class="estimate-range">22–76<small>分钟</small></div><div class="estimate-recommend">这部分建议预留<strong>49 分钟</strong></div></div>
 <p class="scope-note">目前只估识别到的部分。<br>完整任务可能需要更久，外部签字与审批等待不计入。</p>
 <div class="section-title"><h2 style="font-size:13px">时间主要花在哪里</h2></div><ul class="workload-list"><li>填写基础信息、选择或评分<span>2 个字段 · 5 个评分项</span></li><li>回顾经历，写自我评价<span>约 300 字</span></li><li>填写证明名称，准备材料并复核<span>1 个短文本栏</span></li></ul>
 <p class="estimate-assumption">按普通熟悉程度保守估算，假设基础信息可直接取得。</p>
 <div class="estimate-bottom"><button class="quiet" id="toggle-supplement" aria-expanded="false">补充我的情况 <span>＋</span></button><button class="secondary" id="reestimate">重新估算</button></div>
 <div class="supplement" id="supplement-panel" hidden><label for="supplement-text">还有哪些情况会影响用时？</label><textarea id="supplement-text" placeholder="例如：分数已经算好，只需要抄入。">${escapeHTML(state.supplement)}</textarea></div>
 </section><aside class="material-aside"><h3>先知道多久，再决定怎么安排。</h3><p>这只是时间参考。<br>你的计划还没有改变。</p><div class="small-rule"></div><span class="note-label">关于这次估算</span><p style="margin-top:11px">主观文字和准备证明通常比抄写信息更费时间。已经准备好的部分，可以补充说明。</p><div class="small-rule"></div><p>需要加入计划时，还会核对任务内容与安排条件。</p><button class="quiet small" data-detail="confirm">了解确认步骤 ↗</button></aside></div>`}
function touch(){return `${heading('组件与交互','能感觉到，自己按下去了。','只让真正可操作的区域响应。')}<p class="touch-intro">把鼠标移上去，再按住按钮或整行。主操作略微变暗并下沉，次操作收紧，普通文字保持安静。松开后自然回弹；键盘焦点也有清楚的轮廓。</p><div class="touch-grid"><section class="touch-block"><h2>01 / 操作有轻重</h2><p>Primary · Secondary · Quiet</p><div class="touch-controls"><button class="primary" id="touch-primary" data-tactile>帮我安排 <span>→</span></button><button class="secondary" data-tactile>重新估算</button><button class="quiet" data-tactile>查看详情 ↗</button></div></section><section class="touch-block"><h2>02 / 一整行，都能点</h2><p>轻微底色响应，不上浮、不发光。</p><button class="click-row touch-row" id="touch-row" data-tactile><span><strong>常用学习地点</strong><small>图书馆 · 卫津路校区</small></span><span>›</span></button></section></div><div class="touch-spec"><div><strong>移入 / Hover</strong><p>背景轻微加深。<br>布局与文字位置不变。</p></div><div><strong>按下 / Pressed</strong><p>主按钮缩至 97.5%，下移 1px。<br>颜色加深、阴影收进内部。</p></div><div><strong>松开 / Release</strong><p>160ms 内恢复。<br>减少动态效果时保留颜色反馈。</p></div></div><div style="margin-top:37px;padding:17px 0;border-top:1px solid var(--line);font-size:12px;color:var(--muted)">普通信息示例：19:00 在第九教学楼上课。<span style="float:right;font-size:10px">无 hover / 无按压 / 无手型</span></div>`}
function render(scene){state.scene=scene;$('#main').innerHTML=({empty,today,timeline,material,touch}[scene]||today)();$('#breadcrumb').innerHTML='我的工作台 <span>/</span> '+({empty:'今天',today:'今天',timeline:'时间线',material:'材料估时',touch:'交互样式'}[scene]);$$('[data-nav]').forEach(a=>{const active=a.dataset.nav===(scene==='empty'?'today':scene);a.classList.toggle('active',active);a.toggleAttribute('aria-current',active)});$$('[data-scene]').forEach(b=>b.classList.toggle('selected',b.dataset.scene===scene));$('.nav-count').textContent=scene==='empty'?'0':'3';bindMain();window.scrollTo(0,0)}
function go(scene){if(scene==='settings'){openSettings();return}if(scene==='empty')state.hasPlan=false;if(scene==='today'||scene==='timeline')state.hasPlan=true;if(location.hash==='#'+scene)render(scene);else location.hash=scene}
function bindMain(){const plan=$('#plan-form');if(plan){plan.onsubmit=e=>{e.preventDefault();notify('已载入示例计划，原型不处理实际任务。');go('today')};$('#fill-example').onclick=()=>{plan.querySelector('textarea').value='在图书馆写90分钟作业，然后背60分钟单词。19:00去九教上课，上课前吃晚饭。';plan.querySelector('input').value='图书馆';plan.querySelector('textarea').focus()}}
 if($('#toggle-supplement')){$('#toggle-supplement').onclick=()=>{const panel=$('#supplement-panel');panel.hidden=!panel.hidden;$('#toggle-supplement').setAttribute('aria-expanded',String(!panel.hidden));if(!panel.hidden)$('#supplement-text').focus()};$('#supplement-text').oninput=e=>state.supplement=e.target.value;$('#reestimate').onclick=async e=>{const button=e.currentTarget;button.disabled=true;button.textContent='正在估算…';$('#supplement-text').disabled=true;await new Promise(r=>setTimeout(r,700));button.disabled=false;button.textContent='重新估算';$('#supplement-text').disabled=false;notify('重估交互已演示；原型中的分钟仍为示例。')};$('#change-file').onclick=()=>$('#material-file').click();$('#material-file').onchange=()=>notify('已演示文件选择；原型仍展示测评表示例，不读取文件内容。')}
}
function captureSettings(){if(!state.draft)return;$$('[data-pref]').forEach(e=>state.draft[e.dataset.pref]=e.value)}
function settingsContent(){const v=state.draft;const opt=(values,value)=>values.map(t=>`<option ${t===value?'selected':''}>${t}</option>`).join('');const times=(label,a,b)=>`<div class="setting-row"><label>${label}</label><div class="time-pair"><input aria-label="${label}开始" data-pref="${a}" value="${escapeHTML(v[a])}"><span>—</span><input aria-label="${label}结束" data-pref="${b}" value="${escapeHTML(v[b])}"></div></div>`;
 const tabs={preferences:`<section class="settings-group"><h3>安排习惯</h3><div class="setting-row"><label for="travel-pref">常用出行方式<small>有明确要求时，以本次安排为准。</small></label><select id="travel-pref" data-pref="travel">${opt(['步行','骑行'],v.travel)}</select></div><div class="setting-row"><label for="rhythm-pref">学习节奏</label><select id="rhythm-pref" data-pref="rhythm">${opt(['适当穿插休息','希望少切换'],v.rhythm)}</select></div></section><section class="settings-group"><h3>日常用餐</h3>${times('午饭时段','lunchStart','lunchEnd')}${times('晚饭时段','dinnerStart','dinnerEnd')}</section><section class="settings-group"><h3>其他偏好</h3><label for="settings-note" style="font-size:13px">还有什么希望平时记住？</label><textarea id="settings-note" class="settings-note" data-pref="note">${escapeHTML(v.note)}</textarea></section><div class="setting-row"><span>个人档案<small>你的课表、常用地点与偏好</small></span><button class="quiet" data-detail="profile">查看 ›</button></div>`,
 places:`<section class="settings-group"><h3>校园</h3><div class="setting-row"><label for="campus-pref">常用校区</label><select id="campus-pref" data-pref="campus">${opt(['卫津路校区','北洋园校区'],v.campus)}</select></div></section><section class="settings-group"><h3>常去的地方</h3><div class="setting-row"><label for="dorm-pref">宿舍</label><select id="dorm-pref" data-pref="dorm">${opt(['六里台宿舍','暂不设置'],v.dorm)}</select></div><div class="setting-row"><label for="study-pref">常用学习地点</label><select id="study-pref" data-pref="study">${opt(['图书馆','第九教学楼'],v.study)}</select></div></section><p class="muted" style="font-size:11px;line-height:2">常用地点用于减少重复输入，<br>不会被当作你现在所在的位置。</p>`,
 courses:`<section class="settings-group"><h3>本学期</h3><div class="setting-row"><span>启用手动课表<small>按日期与教学周加入固定课程。</small></span><button class="switch" role="switch" aria-checked="true" aria-label="启用手动课表"></button></div><div class="setting-row"><span>教学周</span><span class="muted">2026.08.31 — 2027.01.17</span></div></section><div class="section-title"><h2>课程</h2><button class="quiet" data-detail="import">导入课表 ↗</button></div><div class="course-list"><p>大学英语<small>周二 10:00—11:30 · 第九教学楼 · 第 1—16 周</small></p><p>高等数学<small>周四 08:30—10:00 · 第九教学楼 · 第 1—16 周</small></p></div><p class="muted" style="font-size:11px">保存课表不会立即重排当前方案。</p>`};$('#settings-content').innerHTML=tabs[state.settingsTab];$$('[data-setting-tab]').forEach(b=>{const selected=b.dataset.settingTab===state.settingsTab;b.setAttribute('aria-selected',String(selected));b.tabIndex=selected?0:-1});$$('[data-pref]').forEach(e=>e.addEventListener('input',()=>$('#settings-status').textContent='有未保存的修改。'));const sw=$('.switch');if(sw)sw.onclick=()=>sw.setAttribute('aria-checked',String(sw.getAttribute('aria-checked')!=='true'))}
function openSettings(){state.opener=document.activeElement;state.draft=state.draft||{...state.settings};settingsContent();$('#overlay').hidden=false;$('#settings').hidden=false;$('#app').inert=true;document.body.style.overflow='hidden';$('#close-settings').focus();$$('[data-scene]').forEach(b=>b.classList.toggle('selected',b.dataset.scene==='settings'))}
function closeSettings(){captureSettings();$('#settings').hidden=true;$('#overlay').hidden=true;$('#app').inert=false;document.body.style.overflow='';if(state.opener?.isConnected)state.opener.focus();$$('[data-scene]').forEach(b=>b.classList.toggle('selected',b.dataset.scene===state.scene))}
function detail(kind){const data={why:['为什么先写作业？','示例安排把需要集中注意力的作业放在下午第一段，接着背单词。晚饭和 19:00 的课已经留出位置。这里展示的是安排说明，不新增任务或修改进度。'],next:['接下来：背单词','15:30—16:30 · 图书馆<br>完成这一段后，16:30 收拾东西，再步行去学三食堂。'],route:['出行安排','<div class="ledger-row"><span>16:30</span><span>收拾东西</span><small>5 分钟</small></div><div class="ledger-row"><span>16:35—16:42</span><span>前往学三食堂</span><small>步行约 7 分钟</small></div><div class="ledger-row"><span>18:41</span><span>收拾东西</span><small>5 分钟</small></div><div class="ledger-row"><span>18:46—18:50</span><span>前往第九教学楼</span><small>步行约 4 分钟</small></div><p style="margin-top:16px">18:50 到达，留 10 分钟进楼和课前准备。</p>'],confirm:['加入计划前，先确认','核对要做什么、采用的分钟数，以及是否有截止时间、指定地点或关联已有任务。<br><br>当前示例只覆盖已识别部分，因此这里不提供直接加入按钮。'],profile:['个人档案','这是独立视觉原型中的示例档案。所有编辑只保留在当前页面内，刷新后恢复，不读取或写入正式档案。'],import:['导入课表','这里展示导入入口的位置。正式版本继续使用原课表识别、校对与确认流程。此原型不处理真实课表。'],about:['如何使用这个原型','底部 A—F 切换典型状态。可以编辑输入、展开估时补充、打开设置并保存示例偏好。<br><br>所有计划和分钟都是示例；不调用模型、不写入正式数据。'],feedback:['计划有变化？','告诉我进度、当前位置或临时变化。<textarea class="feedback-box" id="feedback-text" aria-label="告诉 CampusFlow 发生了什么" placeholder="作业还剩40分钟，我现在已经到图书馆了。"></textarea><button class="primary" id="apply-feedback">更新方案 →</button>'],replan:['重新安排今天','<textarea class="feedback-box" aria-label="重新安排今天" placeholder="写下接下来想做的事、时间要求和当前位置。"></textarea><button class="primary" id="apply-feedback">帮我安排 →</button>']};const item=data[kind]||data.about;$('#detail-title').textContent=item[0];$('#detail-content').innerHTML=item[1];$('#detail-dialog').showModal();if($('#apply-feedback'))$('#apply-feedback').onclick=()=>{$('#detail-dialog').close();notify('已演示提交操作；本原型不改变正式计划。')}}
document.addEventListener('click',e=>{const el=e.target.closest('button,a');if(!el)return;if(el.hasAttribute('data-settings'))openSettings();if(el.dataset.scene){if(!$('#settings').hidden)closeSettings();go(el.dataset.scene)}if(el.hasAttribute('data-feedback'))detail('feedback');if(el.hasAttribute('data-replan'))detail('replan');if(el.dataset.detail)detail(el.dataset.detail);if(el.hasAttribute('data-about'))detail('about');if(el.hasAttribute('data-close-detail'))$('#detail-dialog').close();if(el.hasAttribute('data-tactile'))notify('已按下。这里仅演示触感，不执行业务操作。')});
$('#close-settings').onclick=closeSettings;$('#overlay').onclick=closeSettings;$('#save-settings').onclick=()=>{captureSettings();state.settings={...state.draft};$('#settings-status').textContent='示例设置已保存；当前方案未更新。';notify('示例设置已保存，不会立即重排当前方案。')};$$('[data-setting-tab]').forEach(b=>{b.onclick=()=>{captureSettings();state.settingsTab=b.dataset.settingTab;settingsContent()};b.onkeydown=e=>{if(['ArrowLeft','ArrowRight'].includes(e.key)){e.preventDefault();const tabs=$$('[data-setting-tab]'),i=tabs.indexOf(b),next=tabs[(i+(e.key==='ArrowRight'?1:2))%3];next.click();next.focus()}}});
document.addEventListener('keydown',e=>{if($('#settings').hidden||$('#detail-dialog').open)return;if(e.key==='Escape'){e.preventDefault();closeSettings()}if(e.key==='Tab'){const focusables=$$('button,input,select,textarea,[href]', $('#settings')).filter(el=>!el.disabled&&el.tabIndex>=0&&el.getClientRects().length),first=focusables[0],last=focusables.at(-1);if(e.shiftKey&&document.activeElement===first){e.preventDefault();last.focus()}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first.focus()}}});
window.addEventListener('hashchange',()=>{const scene=location.hash.slice(1);if(scene==='settings'){render('today');openSettings()}else render(scene==='today'&&!state.hasPlan?'empty':scene)});
const initial=location.hash.slice(1)||'today';if(initial==='settings'){render('today');openSettings()}else{if(initial==='empty')state.hasPlan=false;render(initial)}
